title: Hållbara Tips
email: your-email@domain.com
permalink: ':title'
baseurl: "/tips" # the subpath of your site, e.g. /blog
url: "https://samuelplumppu.se"

# Author settings
author: Samuel Plumppu
author-pic: samuel.jpg
about-author: "&quot;No one can do everything, but everyone can do something&quot;. Det här är en samling tips som förhoppningsvis väcker en tanke. Att bli en del av lösningen är faktiskt lättare än man kan tro."

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "package-lock.json", "Gemfile", "Gemfile.lock", "assets/css/sass/"]
